"""Tests for HestonModel: pricing, BS/IV helpers, JAX pricer, and calibration.

Calibration tests use small synthetic surfaces generated by the pricer itself so a
round-trip should recover the parameters. The NUTS test runs a tiny sampler -- it
checks plumbing (shapes/keys/return type), not posterior accuracy.
"""
import logging

import jax.numpy as jnp
import numpy as np
import pytest

from src.algorithms.heston import heston_analytics
from src.algorithms.heston.heston_analytics import HestonModel
from src.algorithms.heston.heston_config import (
    HestonCalibrationConfig,
    MSEConfig,
    NUTSConfig,
    QuadConfig,
)
from src.algorithms.heston.heston_params import HestonParams

S_0 = 100.0
R = 0.02
TRUE = HestonParams(v_0=0.04, v_mean=0.04, a=1.5, eta=0.3, rho=-0.6)


def _surface() -> tuple[np.ndarray, np.ndarray]:
    """A small scattered strike/maturity grid flattened to parallel arrays."""
    ks = np.array([90.0, 95.0, 100.0, 105.0, 110.0])
    ts = np.array([0.25, 0.5, 1.0])
    k, t = np.meshgrid(ks, ts)
    return k.ravel(), t.ravel()


@pytest.fixture
def pricer() -> HestonModel:
    return HestonModel(TRUE)


# --------------------------------------------------------------------------- #
# __init__ / Feller diagnostic
# --------------------------------------------------------------------------- #
def test_init_feller_ok_no_warning(caplog: pytest.LogCaptureFixture) -> None:
    with caplog.at_level(logging.WARNING):
        HestonModel(HestonParams(v_0=0.04, v_mean=0.04, a=2.0, eta=0.3, rho=-0.5))
    assert "Feller" not in caplog.text


def test_init_feller_violation_warns(caplog: pytest.LogCaptureFixture) -> None:
    with caplog.at_level(logging.WARNING):
        HestonModel(HestonParams(v_0=0.04, v_mean=0.04, a=0.5, eta=0.5, rho=-0.5))
    assert "Feller" in caplog.text


# --------------------------------------------------------------------------- #
# Analytical pricer
# --------------------------------------------------------------------------- #
def test_call_is_positive_and_decreasing_in_strike(pricer: HestonModel) -> None:
    k = np.array([80.0, 100.0, 120.0])
    t = np.array([1.0, 1.0, 1.0])
    prices = pricer.call(k, S_0, R, t)
    assert np.all(prices > 0)
    assert np.all(np.diff(prices) < 0)  # calls cheaper as strike rises


def test_call_above_intrinsic(pricer: HestonModel) -> None:
    k = np.array([90.0])
    t = np.array([0.5])
    intrinsic = S_0 - k * np.exp(-R * t)
    assert pricer.call(k, S_0, R, t)[0] > intrinsic[0]


def test_call_with_explicit_params_differs(pricer: HestonModel) -> None:
    # exercises the `params is not None` branch across cf/_pi1/_pi2/call
    k = np.array([100.0])
    t = np.array([1.0])
    other = HestonParams(v_0=0.09, v_mean=0.09, a=1.5, eta=0.3, rho=-0.6)
    base = pricer.call(k, S_0, R, t)[0]
    bumped = pricer.call(k, S_0, R, t, params=other)[0]
    assert bumped > base  # higher variance -> pricier call


def test_put_call_parity(pricer: HestonModel) -> None:
    k = np.array([95.0, 105.0])
    t = np.array([0.5, 0.5])
    call = pricer.call(k, S_0, R, t)
    put = pricer.put(k, S_0, R, t)
    np.testing.assert_allclose(put, call - S_0 + k * np.exp(-R * t), rtol=1e-10)


# --------------------------------------------------------------------------- #
# Black-Scholes / implied-vol helpers
# --------------------------------------------------------------------------- #
def test_bs_call_matches_known_value() -> None:
    # ATM, r=0, t=1, sigma=0.2 -> price = S0*(2*Phi(0.1)-1)
    price = HestonModel._bs_call(100.0, 100.0, 0.0, 1.0, 0.2)
    from scipy.stats import norm
    expected = 100.0 * (2 * norm.cdf(0.1) - 1)
    assert price == pytest.approx(expected, rel=1e-12)


def test_bs_vega_positive_and_peaks_atm() -> None:
    k = np.array([80.0, 100.0, 120.0])
    t = np.full(3, 1.0)
    vega = HestonModel._bs_vega(100.0, k, 0.0, t, np.full(3, 0.2))
    assert np.all(vega > 0)
    assert vega[1] == vega.max()  # ATM vega is largest


def test_implied_vol_roundtrip() -> None:
    sigma = 0.27
    price = HestonModel._bs_call(100.0, 105.0, 0.02, 0.75, sigma)
    iv = HestonModel._implied_vol_scalar(price, 100.0, 105.0, 0.02, 0.75)
    assert iv == pytest.approx(sigma, rel=1e-6)


def test_implied_vol_below_intrinsic_is_nan() -> None:
    # price below intrinsic value -> no valid IV
    iv = HestonModel._implied_vol_scalar(1.0, 100.0, 80.0, 0.0, 1.0)
    assert np.isnan(iv)


def test_implied_vol_above_spot_is_nan() -> None:
    iv = HestonModel._implied_vol_scalar(101.0, 100.0, 100.0, 0.0, 1.0)
    assert np.isnan(iv)


def test_implied_vol_brentq_failure_is_nan(monkeypatch: pytest.MonkeyPatch) -> None:
    def _boom(*_args, **_kwargs):  # noqa: ANN002, ANN003
        raise ValueError("no bracket")

    monkeypatch.setattr(heston_analytics, "brentq", _boom)
    iv = HestonModel._implied_vol_scalar(10.0, 100.0, 100.0, 0.0, 1.0)
    assert np.isnan(iv)


def test_implied_vol_vectorised_shape() -> None:
    price = np.array([5.0, 10.0])
    k = np.array([100.0, 95.0])
    t = np.array([1.0, 1.0])
    iv = HestonModel._implied_vol(price, 100.0, k, R, t)
    assert iv.shape == (2,)
    assert np.all(np.isfinite(iv))


# --------------------------------------------------------------------------- #
# JAX pricer
# --------------------------------------------------------------------------- #
def test_gauss_legendre_nodes() -> None:
    nodes, weights = HestonModel._gauss_legendre(200.0, 64)
    assert nodes.shape == (64,)
    assert weights.shape == (64,)
    assert float(nodes.min()) > 0.0
    assert float(nodes.max()) < 200.0
    assert float(weights.sum()) == pytest.approx(200.0, rel=1e-10)  # integrates 1


def test_call_jax_matches_numpy(pricer: HestonModel) -> None:
    k, t = _surface()
    ref = pricer.call(k, S_0, R, t)
    nodes, weights = HestonModel._gauss_legendre(200.0, 128)
    pv = jnp.asarray([TRUE.v_0, TRUE.v_mean, TRUE.a, TRUE.eta, TRUE.rho])
    jx = np.asarray(
        HestonModel._call_jax(pv, jnp.asarray(k), S_0, R, jnp.asarray(t), nodes, weights),
    )
    np.testing.assert_allclose(jx, ref, rtol=1e-6)


# --------------------------------------------------------------------------- #
# MSE calibration
# --------------------------------------------------------------------------- #
def test_mse_optimizer_recovers_params(pricer: HestonModel) -> None:
    k, t = _surface()
    call = pricer.call(k, S_0, R, t)
    start = HestonParams(v_0=0.06, v_mean=0.06, a=2.5, eta=0.45, rho=-0.3)
    fitted = HestonModel(start).mse_optimizer(start, k, S_0, R, t, call)
    for got, exp in zip(
        (fitted.v_0, fitted.v_mean, fitted.a, fitted.eta, fitted.rho),
        (TRUE.v_0, TRUE.v_mean, TRUE.a, TRUE.eta, TRUE.rho),
        strict=True,
    ):
        assert got == pytest.approx(exp, abs=1e-3)


def test_mse_optimizer_drops_invalid_quotes(
    pricer: HestonModel, caplog: pytest.LogCaptureFixture,
) -> None:
    k, t = _surface()
    call = pricer.call(k, S_0, R, t)
    # append one arbitrage-violating quote (price above spot) -> dropped
    k = np.append(k, 100.0)
    t = np.append(t, 0.5)
    call = np.append(call, 2 * S_0)
    with caplog.at_level(logging.WARNING):
        fitted = HestonModel(TRUE).mse_optimizer(TRUE, k, S_0, R, t, call)
    assert "Dropping" in caplog.text
    assert fitted.a == pytest.approx(TRUE.a, abs=1e-2)


def test_mse_optimizer_all_invalid_raises(pricer: HestonModel) -> None:
    k = np.array([100.0, 100.0])
    t = np.array([0.5, 1.0])
    call = np.array([2 * S_0, 3 * S_0])  # both violate no-arb -> nothing to fit
    with pytest.raises(ValueError, match="No valid quotes"):
        HestonModel(TRUE).mse_optimizer(TRUE, k, S_0, R, t, call)


# --------------------------------------------------------------------------- #
# NUTS calibration (tiny smoke run)
# --------------------------------------------------------------------------- #
def test_nuts_optimizer_runs_and_stores_posterior(
    pricer: HestonModel, caplog: pytest.LogCaptureFixture,
) -> None:
    k, t = _surface()
    call = pricer.call(k, S_0, R, t)
    # include one invalid quote so the drop-warning path is exercised too
    k = np.append(k, 100.0)
    t = np.append(t, 0.5)
    call = np.append(call, 2 * S_0)

    cal = HestonModel(TRUE)
    with caplog.at_level(logging.WARNING):
        post = cal.nuts_optimizer(
            TRUE, k, S_0, R, t, call,
            num_warmup=4, num_samples=4, n_quad=16, seed=0,
        )
    assert "dropping" in caplog.text
    assert isinstance(post, HestonParams)
    assert set(cal.posterior) == {"v_0", "v_mean", "a", "eta", "rho", "sigma"}
    # get_samples flattens chains: default num_chains=4 x num_samples=4 = 16
    assert np.asarray(cal.posterior["v_0"]).shape == (NUTSConfig().num_chains * 4,)


def test_nuts_optimizer_all_invalid_raises() -> None:
    k = np.array([100.0, 100.0])
    t = np.array([0.5, 1.0])
    call = np.array([2 * S_0, 3 * S_0])
    with pytest.raises(ValueError, match="No valid quotes"):
        HestonModel(TRUE).nuts_optimizer(TRUE, k, S_0, R, t, call)


# --------------------------------------------------------------------------- #
# optimize_params orchestration (mock the two stages -> fast)
# --------------------------------------------------------------------------- #
def test_optimize_params_runs_both_stages(monkeypatch: pytest.MonkeyPatch) -> None:
    cal = HestonModel(TRUE)
    mse_out = HestonParams(v_0=0.05, v_mean=0.05, a=1.0, eta=0.2, rho=-0.4)
    nuts_out = HestonParams(v_0=0.03, v_mean=0.03, a=2.0, eta=0.25, rho=-0.7)
    calls = {}

    def fake_mse(*, init_params, k, s_0, r, t, call):  # noqa: ANN001, ANN003
        calls["mse_init"] = init_params
        return mse_out

    def fake_nuts(*, init_params, k, s_0, r, t, call):  # noqa: ANN001, ANN003
        calls["nuts_init"] = init_params
        return nuts_out

    monkeypatch.setattr(cal, "mse_optimizer", fake_mse)
    monkeypatch.setattr(cal, "nuts_optimizer", fake_nuts)

    k, t = _surface()
    cal.optimize_params(k=k, s_0=S_0, r=R, t=t, call=np.ones_like(k))
    assert calls["mse_init"] is TRUE              # seeded from self.params
    assert calls["nuts_init"] is mse_out          # NUTS warm-started from MSE
    assert cal.params is nuts_out                 # final params = NUTS result


# --------------------------------------------------------------------------- #
# Calibration config
# --------------------------------------------------------------------------- #
def test_config_defaults_match_legacy() -> None:
    # Defaults must reproduce the pre-refactor hardcoded literals exactly.
    assert QuadConfig().u_max == 200.0
    assert QuadConfig().n_quad == 128
    assert MSEConfig().lb() == [1e-4, 1e-4, 1e-2, 1e-2, -0.999]
    assert MSEConfig().ub() == [1.0, 1.0, 20.0, 5.0, 0.999]
    assert NUTSConfig().num_chains == 4
    assert NUTSConfig().lognormal_scale == 0.5


def test_custom_quad_flows_into_call() -> None:
    # A deliberately coarse grid changes the price -> proves call() reads config.
    k = np.array([100.0])
    t = np.array([1.0])
    fine = HestonModel(TRUE).call(k, S_0, R, t)[0]
    coarse = HestonModel(
        TRUE, HestonCalibrationConfig(quad=QuadConfig(n_quad=8)),
    ).call(k, S_0, R, t)[0]
    assert coarse != pytest.approx(fine, rel=1e-6)


def test_custom_mse_bounds_clip(pricer: HestonModel) -> None:
    # Cap `a` (3rd param) well below its true value -> fit must clip at the bound.
    k, t = _surface()
    call = pricer.call(k, S_0, R, t)
    bounds = (
        (1e-4, 1.0), (1e-4, 1.0), (1e-2, 0.5), (1e-2, 5.0), (-0.999, 0.999),
    )
    cfg = HestonCalibrationConfig(mse=MSEConfig(bounds=bounds))
    start = HestonParams(v_0=0.06, v_mean=0.06, a=0.4, eta=0.45, rho=-0.3)
    fitted = HestonModel(start, cfg).mse_optimizer(start, k, S_0, R, t, call)
    assert fitted.a <= 0.5 + 1e-9


def test_nuts_kwarg_overrides_config() -> None:
    # config asks for many samples; the per-call kwarg overrides it.
    k, t = _surface()
    call = HestonModel(TRUE).call(k, S_0, R, t)
    cfg = HestonCalibrationConfig(nuts=NUTSConfig(num_samples=999, num_warmup=4))
    cal = HestonModel(TRUE, cfg)
    cal.nuts_optimizer(TRUE, k, S_0, R, t, call, num_samples=4, n_quad=16)
    # kwarg num_samples=4 wins over cfg's 999; flattened over default 4 chains -> 16
    assert np.asarray(cal.posterior["v_0"]).shape == (NUTSConfig().num_chains * 4,)
